apiVersion: apps/v1
kind: Deployment
metadata:
  name: clojure-deployment
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/sync-wave: "1"
  spec:
  template:
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
                - key: env
                  operator: In
                  values:
                  - dev
