apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- namespace.yaml

namespace: dev

images:
- name: IMAGE:TAG
  newName: registry.digitalocean.com/nginx-container/clojure
  newTag: "5.0"

labels: # more fine-grain control than commonLabels
  - pairs:
      env: dev
    includeTemplates: true

configMapGenerator:
- name: app-env
  envs:
  - dev.env

generatorOptions:
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous

patchesStrategicMerge:
- add-node-affinity.yaml
