apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- namespace.yaml

namespace: dev

images:
- name: IMAGE:TAG
  newName: registry.digitalocean.com/nginx-container/clojure
  newTag: 9d688574061884f6c49d2bc776598030ac741103

labels:
- includeTemplates: true
  pairs:
    env: dev

configMapGenerator:
- envs:
  - dev.env
  name: app-env

generatorOptions:
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous

patchesStrategicMerge:
- add-node-affinity.yaml
