apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  template:
    spec:
      affinity:
        nodeAffinity:
          prefferedDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              preference:
                matchExpressions:
                  - key: env
                    operator: In
                    values:
                    - staging
