apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base
- namespace.yaml
- staging_config_map.yaml

namespace: staging

images:
- name: IMAGE:TAG
  newName: registry.digitalocean.com/nginx-container/nginx
  newTag: "latest"

patchesStrategicMerge:
- add_node_affinity.yaml
