apiVersion: apps/v1
kind: Deployment
metadata:
  name: clj-deployment
spec:
  template:
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
                - key: env
                  operator: In
                  values:
                  - test
