apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: clj-argo-application
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Lisa-Stats/do-clj-kustomize.git
    targetRevision: HEAD
    path: overlays/dev
  destination:
    server: https://kubernetes.default.svc

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
