apiVersion: apps/v1
kind: Deployment
metadata:
  name: clojure-deployment
  annotations:
    argocd.argoproj.io/hook: Sync
  labels:
    app: clojure
spec:
  replicas: 2
  selector:
    matchLabels:
      app: clojure
  template:
    metadata:
      labels:
        app: clojure
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - clojure
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: clojure
          image: IMAGE:TAG
          ports:
            - containerPort: 8090
          volumeMounts:
            - name: db-url-file
              mountPath: /etc/secret
      volumes:
        - name: db-url-file
          secret:
            secretName: app-environment
