apiVersion: v1
kind: Service
metadata:
  name: clojure-service
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/sync-wave: "1"
spec:
  type: NodePort
  selector:
    app: clojure
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090
