apiVersion: apps/v1
kind: Deployment
metadata:
  name: clojure-deployment
  labels:
    app: clojure
spec:
  replicas: 2
  selector:
    matchLabels:
      app: clojure
  template:
    metadata:
      labels:
        app: clojure
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - clojure
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: clojure
          image: IMAGE:TAG
          ports:
            - containerPort: 8090
          env:
            - name: ENV_TYPE
              valueFrom:
                configMapKeyRef:
                  name: app-env
                  key: env
