apiVersion: apps/v1
kind: Deployment
metadata:
  name: clojure-deployment
  labels:
    app: clojure
spec:
  replicas: 2
  selector:
    matchLabels:
      app: clojure
  template:
    metadata:
      labels:
        app: clojure
    spec:
      serviceAccountName: my-service-account
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - clojure
              topologyKey: "kubernetes.io/hostname"
      initContainers:
          - name: migrations-waiting-init
            image: ghcr.io/groundnuty/k8s-wait-for:v1.6
            imagePullPolicy: IfNotPresent
            args:
              - "job"
              - "migration-job"
      containers:
        - name: clojure
          image: IMAGE:TAG
          ports:
            - containerPort: 8090
          volumeMounts:
            - name: db-url-file
              mountPath: /etc/secret
          env:
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: db-url
                  key: DB_URL
      volumes:
        - name: db-url-file
          secret:
            secretName: app-environment
