apiVersion: batch/v1
kind: Job
metadata:
  name: healthcheck-test
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  ttlSecondsAfterFinished: 100
  backoffLimit: 1
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: healthcheck-test
          image: registry.digitalocean.com/nginx-container/clojure:5.0
          command: ["curl", "localhost:8090/"]
