apiVersion: batch/v1
kind: Job
metadata:
  name: migration-job
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  ttlSecondsAfterFinished: 100
  backoffLimit: 1
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: fake-migration
          image: alpine:latest
          command: ["sleep", "30"]
          env:
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: db-url
                  key: DB_URL
