apiVersion: batch/v1
kind: Job
metadata:
  name: migration-job
spec:
  ttlSecondsAfterFinished: 100
  backoffLimit: 1
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: migration
          image: registry.digitalocean.com/nginx-container/clojure:5.0
          command: ["lein", "repl"]
          #   - "*ns*"
          #   - "(require '[util.migration])"
          #   - "(util.migration/init)"
          env:
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: db-url
                  key: DB_URL
