apiVersion: batch/v1
kind: Job
metadata:
  name: presync-hook-job-example
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  ttlSecondsAfterFinished: 100
  backoffLimit: 1
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: fake-migration
          image: alpine:latest
          command: ["sleep", "45"]
