apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: my-service-account
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: my-service-account
subjects:
- kind: ServiceAccount
  name: my-service-account
